import Head from "next/head";
import Header from "@/components/Header";
import Intro from "@/components/Intro";
import About from "@/components/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>Priyank Rajai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Header />
        <div className="pl-[20px] pr-[20px] max-w-[1280px] m-auto">
          <Intro />
          <About />
        </div>
      </main>
    </>
  );
}
